[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 1

[[main]]
  identifier = "updates"
  name = "Blog"
  url = "blog"
  weight = 2

[[main]]
  identifier = "photo"
  name = "Photo"
  url = "photo"
  weight = 3
