[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 1

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 2

[[main]]
  identifier = "blog"
  name = "Photos"
  url = "photos"
  weight = 3
